[package]
name = "supabase-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
